image:
  # repository: ghcr.io/<GITHUB_OWNER>/frontend
  # tag: "dev"
  repository: ghcr.io/jinsoooooooo/template-frontend
  tag: "main"
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 80
